### ISSUE TITLE
Imap  Adapter Crash

### ISSUE THREAD

**Issue by EMB7374** [Lucky-ESA/ioBroker.imap#108]
When loading new emails adapter crashes and restarts

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <0.2.1>
 - JS-Controller version: <6.0.11> 
 - Node version: <v20.18.0> 
 - Operating system: <Debian GNU/Linux>
![Screenshot 2024-11-04 111709](https://github.com/user-attachments/assets/608db728-3405-4988-b346-3d8e66060ac5)
![Screenshot 2024-11-04 111813](https://github.com/user-attachments/assets/b9e6297e-079e-4f35-82e5-85ae6a30aa51)

**Comment by EMB7374** [comment]
Sorry for bad English, I'm from Germany

**Comment by Lucky-ESA** [comment]
Kannst du eventuell mal von GIT laden. Habe da ein Logeintrag hinzugefügt um zu sehen, was vor dem crash kommt.

Gruß//Lucky

**Comment by EMB7374** [comment]
Guten Morgen
Ich hoffe ich mache es richtig.
1. Ich habe alten Adapter Deinstalliert.
2. Iob in Experten Modus umgestellt.
3. Installieren aus Eigener URL -> Be­nut­zer­de­fi­niert
4. Dann von git CODE -> URL  holen -> einfügen und installieren
5. Nach Installation taucht immer noch die Wahrung 
![Screenshot 2024-11-05 083158](https://github.com/user-attachments/assets/aa9c6ca9-5ea3-43ed-925e-3466a6f04de4)
6. Meine Daten angegeben 
7. 
![Screenshot 2024-11-05 083920](https://github.com/user-attachments/assets/310a481c-841f-4cba-bad5-73024622eb5a)
8. Habe INBOX Ordner gewechselt und Adapter neu gestartet.
9. 
![Screenshot 2024-11-05 084903](https://github.com/user-attachments/assets/67005d51-439b-4c59-82c6-3142b265bf0c)
10. Simulation von Mail Eingang durch verschieben einer mail in Thunderbird 
11. Crash und Restart 
![Screenshot 2024-11-05 085750](https://github.com/user-attachments/assets/dd42f7b1-811e-40b4-895d-bea96739cacd)
12. Kurze zeit später tauch wider Warnung von punkt 5
13. Meine Einstelungen wenn du die brachst 
![Screenshot 2024-11-05 090519](https://github.com/user-attachments/assets/2a2e0671-57b9-4687-a7e7-4cd5f911e4a9)
![Screenshot 2024-11-05 090600](https://github.com/user-attachments/assets/395e018c-5efe-4c81-9384-8a257df59067)
Die sind zu lang. 
Wenn es möglich ist :) das auch noch zu ändern?
Mfg.

**Comment by Lucky-ESA** [comment]
Danke. Kannst du bitte erneut von GIT laden. Ich benötige dann nur diese Ausgabe
![Screenshot 2024-11-05 133419](https://github.com/user-attachments/assets/9d774c3e-9883-4d12-bff6-77e6ffad4bf6)

**Comment by EMB7374** [comment]
Guten Morgen
So alles neu installiert.
1. Warn Meldung nach Installation ist noch da
![Screenshot 2024-11-06 073426](https://github.com/user-attachments/assets/e8c9ef7f-e2f5-414e-b045-29c40eb71943)
2. Habe zu Vorbereitung  par alte mail gelöscht bekomme folgende Meldung. 
![Screenshot 2024-11-06 074225](https://github.com/user-attachments/assets/9999e1a8-5d9a-4738-959a-db36327650e4)
3. Daten in Objekte/IMAP/***/email/email_01 sind nicht entfernt 
4. Jetzt das interessante verhalten beim erster mail  kommt
![Screenshot 2024-11-06 074443](https://github.com/user-attachments/assets/ce943040-d829-481f-a651-173939a9b743)
5. Bei nächsten läuft es alles sauber ab 
![Screenshot 2024-11-06 083343](https://github.com/user-attachments/assets/e1ff0fc8-c30d-4fd3-982a-9b9a597c204b)
6. Starte ich Instanz neu gehen punkte 4 und 5 von vorne los

am sonst keine Errors.
Mfg.

**Comment by Lucky-ESA** [comment]
Die erst Warnmeldung würde ich gerne so lassen. Vielleicht erstelle ich ein Feature Request beiim Admin Adapter.
Lade bitte erneut runter. Jetzt sollte es funktonieren.

**Comment by EMB7374** [comment]
ich teste es morgen muss zu Arbeit
Mfg

**Comment by EMB7374** [comment]
Guten Morgen
Bis jetzt läuft alles gut außer die Admin Warnung am Anfang.
Ich glaube diese Änderungen haben mein Problem gelöst.

Ein par Probleme und Wünsche am Ende. Ich habe gemerkt das emai_01 und 02 , 03 und 04 usw. sind die gleiche.
Änderungen des flag zum Beispiel uid 203 auf Deleted entfernt email 04 aber nicht 03.
Wenn ich richtig verstehe sollte EMAIL datenbaum  aktuellen stand des email Ordner auf dem Server darstellen
und sollte alle Änderungen ob innerhalb oder außerhalb neu eingelesen werden. 
Gerade eben hat sich EMAIL datenbaum aktualisiert von selber ? mit Verzögerung ?

OK ich gleite ab von Thema Problem ist so weit behoben das ich über mein Skript (Alarmanlage sendet email shelly schaltet licht an -> Ersatz für IFTTT und Webhooks (30€ im Jahr)) nachdenken kann.

Wann kommt die verbesserte nächste offizielle Version von Adapter?
 Mfg

**Comment by Lucky-ESA** [comment]
Die 2.2 ist unterwegs und kann erst nach ca. 3 Wochen in Stable. Bei welchem Anbieter bist du?

Gruß//Lucky

**Comment by EMB7374** [comment]
Normal über stable iobroker.net 
Ihr habt da sehr guten Adapter programmiert. Es gibt glaube ich nur euch und die mail das kann nur senden
Mfg

**Comment by Lucky-ESA** [comment]
Wollte nur wissen bei welchem Provider du dein eMail Account hast?

Gruß//Lucky

**Comment by EMB7374** [comment]
GMX morgen probiere ich mit Telekom 

Am 8. November 2024 09:54:51 MEZ schrieb Lucky-ESA ***@***.***>:

**Comment by EMB7374** [comment]
Hab jetzt GMX und T-Online parallel probiert alles OK.

**Comment by EMB7374** [comment]
Warum es ein Konto aktualisiert nach löschen einer mail außerhalb und anderes nicht ?
![Screenshot 2024-11-09 203953](https://github.com/user-attachments/assets/e45247ed-15cc-4231-8a9f-b6d33f7ba19a)
GMX aktualisiert nicht .

**Comment by Lucky-ESA** [comment]
Das bedeutet es wurde der Status einer Mail geändert die nicht in den 10 geladenen Mails vorhanden ist.
Habe mal was getestet. Man könnte einen Ordner mit dem Adapter anlegen, dort die gelöschten Mails einfügen und dann den Ordner wieder löschen. So könnte man eMails löschen.

**Comment by Lucky-ESA** [comment]
Mir gefällt nicht das da keine Daten vorhanden sind wo welche sein sollten. Kannst du eventuell mal auf debug stellen, Adapter starten, dir selber eine neue Mail zusenden und auf das Update warten. Danach mir das Protokoll an github@luckyskills.de zusenden? Danach wieder auf info loglevel stellen.

**Comment by EMB7374** [comment]
Habe gerade gesendet

**Comment by Lucky-ESA** [comment]
Ja danke. Laut diesem Log läuft alles sauber durch. Überwachst du das Postfach INBOX/Somfy? In den Instanz Einstellung gebe ich nur INDEX vor. Hast du da was geändert?

**Comment by Lucky-ESA** [comment]
is fixed with 0.3.0
