### ISSUE TITLE
Imap adapter makes "Sendto" not working in Blockly

### ISSUE THREAD

**Issue by Roellen** [Lucky-ESA/ioBroker.imap#57]
When installing and deinstalling the imap adapter Blockly does not work correctly. 

![112](https://github.com/Lucky-ESA/ioBroker.imap/assets/69198711/c6af19d0-402c-4d7e-b78f-611b57040901)

Matthias Kleine noticed it is this problem: 
Fehler ist: FieldDropdown options must not be an empty array.

**Comment by Lucky-ESA** [comment]
@Roellen Hi, wir können gerne in deutsch weitermachen. Mit ist gerade nicht bekannt das Dropdowns leer sind. Dieses Verhalten kommt wenn ein Code Fehler aufweist. Hast du die aktuelle Stable Version installiert? Wenn ja, dann bitte mal unter Adapter diesen imap suchen und den Button Dateiupload anklicken.

**Comment by Roellen** [comment]
Hab erstmal 5 Minuten Lebenszeit verloren weil ich nicht wusste, dass man zuerst den Expertenmodus aktivieren muss damit man den Upload button sieht. :-) 

Hab ich jetzt gemacht. (den upload)
Was passiert dann? Kommt dann irgendein Logfile bei Dir an?

**Comment by Lucky-ESA** [comment]
Damit sollten die Daten erneut in den Adminordner geladen werden. Funktioniert denn danach sendTo wieder? Kann deine Ansicht nicht reproduzieren. Hast du denn ein Mailkonto schon angelegt? In der latest Version hatte ich mal einen Fehler auf`m GIT der das verursacht. Vielleicht hast du diese Datei noch bei dir im System...Sollte aber dann mit upload überschrieben werden.
Hast du denn die aktuelle Stable Version installiert?

**Comment by Roellen** [comment]
0.1.2 hab ich installiert. 

Blockly hatte schon wieder funktioniert nachdem ich den IMAP Adapter wieder installiert hatte. 
Vielleicht funktioniert Blockly wieder nicht, wenn ich IMAP deinstalliere. (weil, dann fehlt irgendwas und alles wird falsch angezeigt, sagt Matthias Kleine... ist gerade bei ein paar anderen Adaptern auch das Problem)
Aber... wenn ich der einzige bin der das Problem hat - vielleicht ist es ja doch kein generelles Problem.

**Comment by Lucky-ESA** [comment]
Das konnte ich jetzt nachvollziehen. Wird der Adapter gelöscht kommt deine Anzeige. Hier muss dann der Ordner /opt/iobroker/iobroker-data/files/imap.admin gelöscht werden.
Scheint wohl eher eine fehler im admin oder js-contoller zu sein. Oder es muss vielleicht mal neu gestartet werden.

**Comment by Roellen** [comment]
Neu starten hatte ich auch mal probiert. Hat bei mir nicht geholfen. 

Fühlt sich an als wenn nach dem Löschen irgendwelche Einträge irgendwo fehlen und nicht "ordnungsgemäß" entfernt werden oder sowas. (nur eine Vermutung)
Ich lass den IMAP Adapter jetz einfach mal installiert, ohne ihn zu benutzen. Der hat mir nämlich meinen JS Controller immer lahm gelegt, selbst wenn ich nur einen Datenpunkt (Anzahl ungelesene emails abgerufen habe)

**Comment by Lucky-ESA** [comment]
Das der imap Adapter den JS-Controller lahm legt kann ich mir nicht vorstellen. Lese dir mal die Anleitung durch was du am besten in der Instanz einstellen musst. Du kannst gerne mich über diesen [Thread](https://forum.iobroker.net/topic/63400/test-adapter-iobroker-imap-v0-1-1-latest-stable/347?_=1709406857489) anschreiben. Nicht das ich da ein Problem habe...Aber zurück zu diesen issues. Ich kann da nichts machen werde aber mal die Fragen stellen, warum dieser Ordner nicht gelöscht wird bzw. warum der javascript Adapter die Datei lädt.

**Comment by Lucky-ESA** [comment]
Was mir gerade noch eingefallen ist, du musst den Adapter unter Adapter löschen und nicht nur unter Instanzen. Dann sollte auch wieder sendTo funktionieren.

**Comment by Roellen** [comment]
Tatsache! Wenn man unter Adapter den Adapter löscht, dann gehts. 

Irgendwie doof gemacht von iobroker, dass man den Adapter auch in den Instanzen löschen kann, das dann aber falsch ist.

**Comment by Lucky-ESA** [comment]
Eigentlich wäre es richtig. Ich werde für diesen Fall die Dropouts **NICHT** füllen. Finde es doch falsch, dass bei keiner vorhandenen  Instanz noch immer die Blocklys zur Verfügung stehen.

**Comment by Lucky-ESA** [comment]
Fixed with [commit](https://github.com/Lucky-ESA/ioBroker.imap/commit/783b79e070002486fadd18fa47ec0204d4569711)
